# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='first')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='last')),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True, verbose_name='initial')),
            ],
        ),
    ]
