# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErgScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='00:00.0', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ErgTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('2', '2k'), ('6', '6k'), ('3', '30min')], default='2k', max_length=10)),
                ('date', models.DateField()),
                ('scores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erg.ErgScore')),
            ],
        ),
    ]
