# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erg', '0006_auto_20161031_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ergtest',
            name='scores',
        ),
    ]
