# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erg', '0008_auto_20161031_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ergscore',
            name='name',
        ),
    ]
