# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.DateField()),
                ('position', models.CharField(choices=[('P', 'Port'), ('S', 'Starboard'), ('B', 'Both'), ('N', 'None Listed')], default='N', max_length=2)),
                ('scull', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
            ],
            options={
                'permissions': (('read_tests', 'Can read test scores'), ('modify_tests', 'Can modify test scores')),
            },
        ),
    ]
