# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_coxwain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coxwain',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
