# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_auto_20161021_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rower',
            old_name='age',
            new_name='dob',
        ),
    ]
