# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_auto_20161021_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='rower',
            name='twoK',
            field=models.TimeField(default='7:00'),
        ),
    ]
