# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_auto_20161025_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='erg_6k',
            field=models.CharField(default='00:00.0', max_length=6),
        ),
    ]
