# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0011_auto_20161025_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coxwain',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rower',
            name='name',
        ),
        migrations.AddField(
            model_name='coxwain',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coxwain',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rower',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rower',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
