# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0012_auto_20161025_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='erg_scores',
            field=models.ManyToManyField(null=True, to='athletes.ErgTest'),
        ),
    ]
