# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0014_auto_20161025_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rower',
            options={},
        ),
        migrations.RemoveField(
            model_name='rower',
            name='erg_scores',
        ),
    ]
